### ISSUE TITLE
Possible merge

### ISSUE THREAD

**Issue by bmcorser** [tehmaze/python-multihash#5]
Hi @tehmaze @moreati,

I implemented Multihash around the same time you did, but slightly differently ... want to merge?

I've opened an issue over at https://github.com/ipfs/py-ipfs/issues/13 to discuss.

Cheers,

Ben

**Comment by tehmaze** [comment]
Better late than never, but do you still want to merge into a single package? We can merge your version and use the multihash package name on PyPi if you still desire to do so.

**Comment by tehmaze** [comment]
Started merging in the [bmcorser-py-multihash](/tehmaze/python-multihash/tree/bmcorser-py-multihash) branch, let me know what you think.

I did the following:
* Support `multihash.encode`, `multihash.is_valid_code` and `multihash.is_app_code` like the old interface
* Made sure that `pep8` and `pep257` are happy (100% doc coverage).

**Comment by bmcorser** [comment]
Cool `:)`

I probably should have closed this, but haven't had any time (or particular inclination) work on IPFS stuff recently. To fill you in, it seems like this discussion in ipfs/py-ipfs#13 moved over to https://github.com/ipfs/py-ipfs/issues/23#issuecomment-158345821 and spawned a couple _more_ implementations. I'm not bothered about getting into an arms race, so will probably retire my implementation. Feel free to take what you need!

**Comment by bmcorser** [comment]
Just ran [a compare](https://github.com/tehmaze/python-multihash/compare/bmcorser-py-multihash?expand=1) on the branch you mentioned. What a complement `:D`

Great to see you took the Tox and TravisCI stuff, very cool.

**Comment by bmcorser** [comment]
But this guy seems to have done a pretty comprehensive job: https://github.com/ivilata/pymultihash `:/`

**Comment by tehmaze** [comment]
Indeed a nice and complete implementation, except that in my benchmarks it's much slower (almost twice as slow):

    ivilata-pymultihash% PYTHONPATH=. python3.4 -mtimeit 'import multihash' 'multihash.digest("hello world!".encode("utf8"),"sha1")'
100000 loops, best of 3: 8.68 usec per loop
    python-multihash% PYTHONPATH=. python3.4 -mtimeit 'import multihash' 'multihash.encode("hello world!".encode("utf8"),"sha1")'
100000 loops, best of 3: 4.73 usec per loop

**Comment by bmcorser** [comment]
`:o`

I didn't look at his code whatsoever, just saw the impressive docs and noted that it appears to be "accepted" by other py-ipfs ppl. Happy to help if you want to merge our now-combined work into that guys impl!
